# Generated by Django 5.0.2 on 2024-02-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
