# Generated by Django 5.0.2 on 2024-02-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_user', '0002_alter_staffuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Assistant', 'Assistant'), ('Staff', 'Staff'), ('Researcher', 'Researcher')], max_length=30),
        ),
    ]
