# Generated by Django 5.0.2 on 2024-02-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_user', '0003_alter_staffuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
