# Generated by Django 5.0.2 on 2024-03-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_user', '0004_alter_staffuser_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='office',
            field=models.CharField(choices=[('HOD', 'Hod'), ('UG', 'Ug'), ('PG', 'Pg'), ('TA', 'Ta')], default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Coordinator', 'Coordinator'), ('Staff', 'Staff')], max_length=30),
        ),
    ]
