# Generated by Django 5.0.2 on 2024-06-02 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_user', '0005_staffuser_office_alter_staffuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'office',
            },
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='office',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='role',
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='staff_user.office')),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Administrator', 'Administrator'), ('Coordinator', 'Coordinator'), ('Staff', 'Staff'), ('Head', 'Head')], default='Staff', max_length=50)),
                ('work_role', models.CharField(choices=[('Assistant', 'Assistant'), ('Lecturer', 'Lecturer')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='staff_user.office')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='staff_user.section')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
    ]
