# Generated by Django 5.0.2 on 2024-06-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_user', '0006_office_remove_staffuser_office_remove_staffuser_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='name',
        ),
    ]
