# Generated by Django 5.0.2 on 2024-06-02 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_user', '0007_remove_roles_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='staff_user.section'),
        ),
    ]
