# Generated by Django 5.0.2 on 2024-06-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_user', '0008_alter_roles_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='work_role',
            field=models.CharField(choices=[('Assistant', 'Assistant'), ('Lecturer', 'Lecturer'), ('Secretary', 'Secretary')], max_length=50),
        ),
    ]
