# Generated by Django 5.0.2 on 2024-05-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='schedule_time',
            field=models.DateTimeField(),
        ),
    ]
