# Generated by Django 5.0.2 on 2024-05-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_schedule', '0002_alter_eventschedule_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinvitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='eventinvitation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
