# Generated by Django 5.0.2 on 2024-03-31 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Project Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Project Description (Optional)')),
                ('expected_start_date', models.DateField(blank=True, null=True, verbose_name='Expected Start Date')),
                ('expected_end_date', models.DateField(blank=True, null=True, verbose_name='Expected End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='ProjectAccessTable',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project')),
            ],
            options={
                'db_table': 'project_access_table',
            },
        ),
        migrations.CreateModel(
            name='ProjectAccessRoleTable',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('access_role', models.CharField(choices=[('Contributor', 'Contributor'), ('Viewer', 'Viewer'), ('Commenter', 'Commenter')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Staff User')),
                ('project_access_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectaccesstable', verbose_name='Project Access Table')),
            ],
            options={
                'db_table': 'project_access_role_table',
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Task Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Task Description (Optional)')),
                ('task_weight', models.FloatField(blank=True, null=True, verbose_name='Task Weight Value')),
                ('progress', models.CharField(choices=[('Open', 'Open'), ('Working', 'Working'), ('Pending', 'Pending'), ('Overdue', 'Overdue'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project')),
            ],
            options={
                'db_table': 'project_task',
            },
        ),
        migrations.CreateModel(
            name='ProjectTaskAssignment',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projecttask')),
            ],
            options={
                'db_table': 'project_task_assignment',
            },
        ),
        migrations.CreateModel(
            name='ProjectTaskDependency',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depends_on', to='projects.projecttask')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_task', to='projects.projecttask')),
            ],
            options={
                'db_table': 'project_task_dependency',
            },
        ),
    ]
