# Generated by Django 5.0.2 on 2024-04-03 06:57

import apps.projects.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTaskAttachment',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('attachment', models.FileField(upload_to=apps.projects.models.attachment_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projecttask')),
            ],
            options={
                'db_table': 'project_task_attachment',
            },
        ),
        migrations.CreateModel(
            name='ProjectTaskComment',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commented_on', to='projects.projecttask')),
            ],
            options={
                'db_table': 'project_task_comment',
            },
        ),
    ]
