# Generated by Django 5.0.2 on 2024-04-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projecttaskattachment_projecttaskcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='progress',
            field=models.CharField(choices=[('Open', 'Open'), ('Working', 'Working'), ('Pending', 'Pending'), ('Overdue', 'Overdue'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Open', max_length=50),
        ),
    ]
