# Generated by Django 5.0.2 on 2024-04-03 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projecttask_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='projectaccessroletable',
            name='access_role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Contributor', 'Contributor'), ('Viewer', 'Viewer'), ('Commenter', 'Commenter')], max_length=20),
        ),
    ]
