# Generated by Django 5.0.2 on 2024-04-29 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectaccessroletable',
            name='project_access_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_role_table', to='projects.projectaccesstable', verbose_name='Project Access Table'),
        ),
        migrations.AlterField(
            model_name='projectaccesstable',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_table', to='projects.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='projecttaskassignment',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee', to='projects.projecttask'),
        ),
        migrations.AlterField(
            model_name='projecttaskattachment',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachment', to='projects.projecttask'),
        ),
        migrations.AlterField(
            model_name='projecttaskcomment',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='projects.projecttask'),
        ),
    ]
