# Generated by Django 5.0.2 on 2024-04-29 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectaccessroletable_project_access_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='Project'),
        ),
    ]
