# Generated by Django 5.0.2 on 2024-04-29 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projecttask_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttaskcomment',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='projects.projecttask'),
        ),
    ]
